# Generated by Django 3.2.20 on 2024-06-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Led',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(verbose_name='Key')),
                ('title', models.CharField(default='Untitled', max_length=100, verbose_name='Led Title')),
                ('time_on', models.IntegerField(verbose_name='Time ON')),
                ('time_off', models.IntegerField(verbose_name='Time OFF')),
                ('simulation_time', models.IntegerField(verbose_name='Simulation time')),
            ],
            options={
                'verbose_name_plural': 'Led',
            },
        ),
        migrations.CreateModel(
            name='LedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(verbose_name='Led key')),
                ('times_on', models.IntegerField(verbose_name='Times ON')),
                ('times_off', models.IntegerField(verbose_name='Times OFF')),
                ('number_cycle', models.IntegerField(verbose_name='Number of Cycles')),
                ('simulation_time', models.IntegerField(verbose_name='Simulation time')),
            ],
            options={
                'verbose_name_plural': 'Led Result',
            },
        ),
    ]
