# Generated by Django 3.2.20 on 2024-07-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_simulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='time',
            field=models.IntegerField(verbose_name='Led Time'),
        ),
    ]
